[tool.poetry]
name = "Mercator"
version = "0.1.0"
description = ""
authors = ["Me <maldonadojsm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
coverage = "^5.5"
coveralls = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
